### ISSUE TITLE
Ładowanie jsów w index.html

### ISSUE THREAD

**Issue by senghe** [JavaDevMatt/EvilSlimeCity#1]
Hej, widzę że wszystkie pliki includujesz w index.html jako "<script>". Polecam Ci zaznajomić się z systemem importów plików w ecma script 6 (piszę, bo słyszałem na filmiku że chcesz nauczyć się jak jsy się powinno pisać).

**Comment by JavaDevMatt** [comment]
Dzięki za sugestię - pierwsze o tym słyszę. Właśnie takie importowanie wydawało mi się to trochę dziwne i czegoś mi tu brakowało.

**Comment by senghe** [comment]
Spoko :D polecam link:

http://es6-features.org/#ValueExportImport

I w ogóle dobrze znać wszystko z tej strony :)

**Comment by jpacanowski** [comment]
Hej, taka mała uwaga, że komentarze w HTML zaczyna się od `<!--` a kończy się poprzez `-->`
A nie poprzez // tak jak ty użyłeś.

**Comment by JavaDevMatt** [comment]
Z rozpędu te // w sekcji head. Trzeba poprawić.
