### ISSUE TITLE
Wykorzystanie zmiennych const i let

### ISSUE THREAD

**Issue by Baakoma** [JavaDevMatt/EvilSlimeCity#2]
Cześć, z tego co zauważyłem, to korzystasz ze zmiennych var. W nowej wersji JS, a z tego co widzę, że korzystasz z nowej wersji(m.in. class) dobrą praktyką jest używanie zmiennych const i let, które działają w sposób bardziej zbliżony do zmiennych z innych języków(m.in. zasięg blokowy).
https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75#.bc4ad37xm

Swoją drogą polecam książkę "JavaScript. Programowanie zaawansowane" - zdecydowanie warta swojej ceny
http://helion.pl/ksiazki/javascript-programowanie-zaawansowane-tomasz-comandeer-jakut,jascpz.htm

Warto by było też zapoznać się z narzędziami [babel](https://babeljs.io/) , czy [gulp](http://gulpjs.com/), a nawet [eslint](http://eslint.org/docs/user-guide/getting-started).

**Comment by JavaDevMatt** [comment]
Cześć, te let już mi się o uszy obiło. Nie interesowałem się jeszcze tym co jest w starym i nowym js. Często robiłem coś na zadzie "jak to zrobić w Javie?" i później to robię w JS ;) co na pewno nie jest najlepszym pomysłem - stąd też też te rozwiązania z class. Dzięki za garść linków!

**Comment by Baakoma** [comment]
Proponowałbym Ci od razu zapoznać się z całym nowym ES6, nie ma co wracać do starego - nowy jest zdecydowanie przyjemniejszy :) (choć nie taki nowy, nadchodzi ES7). Jednak, aby nowy ES6 działał na starszych przeglądarkach warto wykorzystać narzędzie babel, które "przekompiluje" Twój kod na starszą wersję, przy okazji warto wykorzystać narzędzie gulp, które zrobi z Twojego kodu ładną paczkę i wszystko wrzucisz jako jeden plik JS (z pewnymi pluginami). Pewnie większość z tych rzeczy wiesz, ale może warto o tym wspomnieć :)

**Comment by jpacanowski** [comment]
Dobrą praktyką byłoby uruchamianie kodu JS w trybie ścisłym -> "use strict";
[http://blog.kamilbrenk.pl/javascript-i-strict-mode/](url)
